# Generated by Django 4.2.5 on 2023-09-21 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='profileImg',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
