# Generated by Django 4.2.5 on 2023-09-21 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herapp', '0002_people_profileimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='profileImg',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
